version: '3'

services:
  mongo:
    image: mongo:3.6-xenial
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
  server-app:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    environment:
      - MONGO_ADDRESS=mongodb://mongo:27017/
