version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "4080:80"
      - "4443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  mongo:
    image: mongo:latest
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - /Users/kranto/tmp/islantidata:/data/db
    ports:
      - "27017:27017"
  react-app:
    build: ..
    volumes:
      - client-app:/app/build
  server-app:
    build: ../server
    ports:
      - "4000:4000"
    environment:
      - MONGO_ADDRESS=mongodb://mongo:27017/
    volumes:
      - client-app:/usr/src/app/islanti

volumes:
  client-app: