version: '3'

services:
  mongo:
    image: mongo:3.6-xenial
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
  client-app:
    image: kranto/islanti-client:latest
    build: 
      context: ../client
    command: /bin/bash -c exit
    volumes:
      - client-app:/app/client/build
  server-app:
    image: kranto/islanti-server:latest
    build: ../server
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    environment:
      - MONGO_ADDRESS=mongodb://mongo:27017/
    volumes:
      - client-app:/app/client

volumes:
  client-app:
